[package]
name = "rust"
version = "0.1.0"
authors = ["BenjiReis <benjamin.reis@vates.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xenctrl-sys = { git = "https://github.com/Wenzel/xenctrl-sys" }

