#include <stdio.h>
#include <xenctrl.h>

#define XSTR(X) STR(X)
#define STR(X) #X

#define DECLARE_HVM_SAVE_VARIABLES(X) \
  printf("pub const HVM_SAVE_LENGTH_" XSTR(X) ": u32 = %zu;\n", HVM_SAVE_LENGTH(X)); \
  printf("pub const HVM_SAVE_CODE_" XSTR(X) ": u16 = %zu;\n\n", HVM_SAVE_CODE(X));

int main (int argc, char *argv[]) {
  (void)argc;
  (void)argv;

  DECLARE_HVM_SAVE_VARIABLES(HEADER);
  DECLARE_HVM_SAVE_VARIABLES(CPU);
  DECLARE_HVM_SAVE_VARIABLES(PIC);
  DECLARE_HVM_SAVE_VARIABLES(IOAPIC);
  DECLARE_HVM_SAVE_VARIABLES(LAPIC);
  DECLARE_HVM_SAVE_VARIABLES(LAPIC_REGS);
  DECLARE_HVM_SAVE_VARIABLES(PCI_IRQ);
  DECLARE_HVM_SAVE_VARIABLES(ISA_IRQ);
  DECLARE_HVM_SAVE_VARIABLES(PCI_LINK);
  DECLARE_HVM_SAVE_VARIABLES(PIT);
  DECLARE_HVM_SAVE_VARIABLES(RTC);
  DECLARE_HVM_SAVE_VARIABLES(HPET);
  DECLARE_HVM_SAVE_VARIABLES(PMTIMER);
  DECLARE_HVM_SAVE_VARIABLES(MTRR);
  DECLARE_HVM_SAVE_VARIABLES(VIRIDIAN_DOMAIN);
  DECLARE_HVM_SAVE_VARIABLES(VIRIDIAN_VCPU);
  DECLARE_HVM_SAVE_VARIABLES(VMCE_VCPU);
  DECLARE_HVM_SAVE_VARIABLES(TSC_ADJUST);
  DECLARE_HVM_SAVE_VARIABLES(END);

  return 0;
}
