#include <xenctrl.h>
#include <xenstore.h>

// Workaround to wrap HvmSaveTypes.
// We can't use `HVM_SAVE_TYPE(X)` in rust.
#define XENOPS_DECLARE_HVM_SAVE_TYPE(X, NAME) \
  typedef HVM_SAVE_TYPE(X) HvmSaveType ## NAME

XENOPS_DECLARE_HVM_SAVE_TYPE(HEADER, Header);
XENOPS_DECLARE_HVM_SAVE_TYPE(CPU, Cpu);
XENOPS_DECLARE_HVM_SAVE_TYPE(PIC, Pic);
XENOPS_DECLARE_HVM_SAVE_TYPE(IOAPIC, Ioapic);
XENOPS_DECLARE_HVM_SAVE_TYPE(LAPIC, Lapic);
XENOPS_DECLARE_HVM_SAVE_TYPE(LAPIC_REGS, LapicRegs);
XENOPS_DECLARE_HVM_SAVE_TYPE(PCI_IRQ, PciIrq);
XENOPS_DECLARE_HVM_SAVE_TYPE(ISA_IRQ, IsaIrq);
XENOPS_DECLARE_HVM_SAVE_TYPE(PCI_LINK, PciLink);
XENOPS_DECLARE_HVM_SAVE_TYPE(PIT, Pit);
XENOPS_DECLARE_HVM_SAVE_TYPE(RTC, Rtc);
XENOPS_DECLARE_HVM_SAVE_TYPE(HPET, Hpet);
XENOPS_DECLARE_HVM_SAVE_TYPE(PMTIMER, Pmtimer);
XENOPS_DECLARE_HVM_SAVE_TYPE(MTRR, Mtrr);
XENOPS_DECLARE_HVM_SAVE_TYPE(VIRIDIAN_DOMAIN, ViridianDomain);
XENOPS_DECLARE_HVM_SAVE_TYPE(VIRIDIAN_VCPU, ViridianVcpu);
XENOPS_DECLARE_HVM_SAVE_TYPE(VMCE_VCPU, VmceVcpu);
XENOPS_DECLARE_HVM_SAVE_TYPE(TSC_ADJUST, TscAdjust);
XENOPS_DECLARE_HVM_SAVE_TYPE(END, End);
